### ISSUE TITLE
crane 内部算法模块的离线评估 

### ISSUE THREAD

**Issue by 497429018** [gocrane/creator#2]
希望能提供一些 更加小白 简易一些的教程或者手册
1、整体架构 或者 数据流图？
2、如何部署,配置有哪些？
3、整个过程如何执行？
4、提供demo 实例 说明如何使用？

**Comment by xieydd** [comment]
`creator` 是 crane 的算法的 python 实现模块以及算法评估模块，旨在为 crane 采用的个人和组织提供具体可离线验证的能力。

所以这里我回答以上您的几个问题：
1. 整体架构
your data -> crane python algorithm -> evaluation indicators -> fit your enviroment

2. 这里提供了部署文档供您使用，可以在本地有 docker 的环境下使用 https://github.com/gocrane/creator#jupyter-lab
3. 我们在 https://github.com/gocrane/creator/tree/main/v1/evaluation 提供了周期性判断算法、预测算法、以及 evpa 算法分别进行了评估，这里更多的是评估的流程和方法论，具体的代码需要根据您的真实环境进行调整
4. 在 jupyter 中有较为详细的文档可以参考

**Comment by xieydd** [comment]
不过这里我们确实看到 creator 对于非算法人员的门槛较高，这里我觉的可以针对不同的任务提供一个可执行 python 程序进行使用，例如针对周期性判断算法：
```
$ python is_periodicity.py --data ./data --format json --sample_interval 30s --cycle_duration 86400s
your data is periodicity, and cycle is 1d.
```

**Comment by xieydd** [comment]
add demo already, https://github.com/gocrane/creator/tree/add_is_periodicity_demo/v1/algorithm/examples
